version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "express"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fwqa6sn45khl"
s3_prefix = "express"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
